export const COUNTER_INCREMENT = "COUNTER_INCREMENT";
export const COUNTER_DECREMENT = "COUNTER_DECREMENT";

export const ADDITION = "ADDITION";
export const SUBSTRACTION = "SUBSTRACTION";
export const MULTIPLICATION = "MULTIPLICATION";
export const DIVISON = "DIVISON";
export const SET_INPUT = "SET_INPUT";
